// src/exporter.ts
//
// Pure builders for the plugin's export formats. The vault writer and the
// "copy all" clipboard action both call `buildBundleMarkdown()` so a project
// copied to the clipboard is byte-identical to the one saved as a bundle note.
//
// Dependency-free (no `obsidian` import) so it can be unit-tested directly.

import { GeneratedFile } from "./types";

/** Fence a code block, widening the fence when the content itself contains backticks. */
export function fenceCode(content: string, language: string): string {
  const longestRun = (content.match(/`+/g) ?? []).reduce((max, run) => Math.max(max, run.length), 0);
  const fence = "`".repeat(Math.max(3, longestRun + 1));
  return `${fence}${language || "text"}\n${content}\n${fence}`;
}

/**
 * Render every generated file into a single Markdown document: YAML frontmatter
 * (so Obsidian indexes it), a heading, then one fenced block per file prefixed
 * with its path.
 */
export function buildBundleMarkdown(
  projectName: string,
  files: GeneratedFile[],
  timestamp: string
): string {
  const body = files
    .map((file) => `## \`${file.path}\`\n\n${fenceCode(file.content, file.language)}`)
    .join("\n\n");

  return [
    "---",
    `project: ${projectName.replace(/"/g, "'")}`,
    `generated: ${timestamp}`,
    `files: ${files.length}`,
    "tags: [fullkonk, bundle]",
    "---",
    "",
    `# ${projectName} — bundle`,
    "",
    `Generated by **fullKONK_>** · ${files.length} file${files.length === 1 ? "" : "s"}`,
    "",
    body,
    "",
  ].join("\n");
}
